spring:
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    url: jdbc:mysql://mysql:3306/local_database
    username: local_username
    password: local_password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true